server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: "!Odero@Mkuu1"
    url: jdbc:mysql://localhost:3306/userman?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: odero
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true